### ISSUE TITLE
Configuración de probabilidad de lluvia

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#10]
Como usuario
quiero poder configurar el nivel de lluvia mínimo, y recibir notificaciones cuando el clima supere mi valor establecido
para estar preparado para cuando vaya a llover

**Descripción**
Agregar un botón de configuración según el mockup, que nos permita cambair un valor (porcentaje) de mínimo de lluvia (usar un modal con un campo numérico). Valor default: 10% (confirmar?)

![image](https://user-images.githubusercontent.com/19612265/94633559-11b68b00-02a4-11eb-9b39-b011400364bf.png)

Este valor debe almacenarse, y periódicamente mientras no se esté usando la aplicación, realizar requests en background al servidor. Si la probabilidad de lluvia supera el límite establecido por el usuario, enviar una push notification, con el mensaje "¡Si vas a salir no te olvides el paraguas!” (**TBD**: título, icono, etc de la notificacion)

**Criterio de aceptación**

Se debe poder configurar mayor a que % de probabilidad de lluvia quiero que me llegue una notificación: “ ¡Si vas a salir no te olvides el paraguas!”

**Comment by MatiasReimondo** [comment]
![6](https://user-images.githubusercontent.com/15663140/95026586-b6e8af00-0668-11eb-814e-122730dfae54.jpg)
![7](https://user-images.githubusercontent.com/15663140/95026587-b7814580-0668-11eb-9f6c-51c69dc3cd75.jpg)
