### ISSUE TITLE
Preservar proporciones en modo portrait y landscape

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#11]
Como usuario
Quiero que la aplicación se vea bien tanto en formato portrait y landscape
para mantener consistencias en la experiencia

**Descripción**
Diseñar y/o realizar ajustes necesarios para que la aplicación se vea bien tanto en modo portrait (vertical) como landscape (horizontal). Mantener las proporciones entre los textos y el tamaño de pantalla entre ambos formatos, sin realizar modificaciones de UI.

**Criterio de aceptación**
La aplicación deberá visualizarse correctamente en modo portrait y no cambiar las proporciones cuando se pasa a modo landscape.

**Comment by Azowyl** [comment]
![Screenshot_1601933333](https://user-images.githubusercontent.com/26676533/95134091-aa338c00-0738-11eb-9c47-ac080a071d02.png)
![Screenshot_1601933342](https://user-images.githubusercontent.com/26676533/95134113-b15a9a00-0738-11eb-8ca0-89187e110213.png)
