### ISSUE TITLE
Valores de fallback cuando no se establece conexión al servidor

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#5]
Como usuario
quiero que, ante un error de conexión con el servidor, se muestren valores por defecto y se me notifique debidamente de los problemas
para estar informado de la situación

**Descripción**
Tanto el clima como la temperatura deberán mostrarse como "S/D" 
Deberá aparecer un toast con el mensaje "No fue posible conectarse al servidor, por favor reintente más tarde" en pantalla

**Criterio de aceptación asociado:**
Si ingreso y no hay conectividad, los valores se deben establecerse en S/D y debe aparecer un mensaje toast indicando “No fue posible conectarse al servidor, por favor reintente más tarde”.

**Comment by MatiasReimondo** [comment]
![1](https://user-images.githubusercontent.com/15663140/95026404-70468500-0667-11eb-890d-ce32a4a60ca2.jpg)

**Comment by MatiasReimondo** [comment]
![2](https://user-images.githubusercontent.com/15663140/95026429-9ec46000-0667-11eb-99d0-69dd67f437b1.jpg)
