### ISSUE TITLE
Selección de Ciudades

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#6]
Como usuario
quiero ver el selector de ciudades en "Buenos Aires"
para estar informado de qué ciudad estoy viendo el clima actual

**Descripción** 
Agregar un campo (search) que esté, por defecto, seleccionado en "Buenos Aires". No es necesario agregar otras ciudades ni permitirle al usuario modificar esta información, simplemente crear la UI para sentar las bases de que, a futuro, la ciudad sea modificable.

![image](https://user-images.githubusercontent.com/19612265/94632757-db780c00-02a1-11eb-86a1-bbe17c1b95d5.png)

**Criterio de aceptación asociado:**
Se debe seleccionar la ciudad de Buenos Aires, para que en una segunda etapa se pueda seleccionar entre diferentes ciudades.

**Comment by MatiasReimondo** [comment]
![3](https://user-images.githubusercontent.com/15663140/95026449-c9aeb400-0667-11eb-941c-ff3cf1c6676c.jpg)
