### ISSUE TITLE
Mostrar temperatura y probabilidad de lluvia

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#7]
Como usuario
Quiero que al entrar a la aplicación se muestre la temperatura actual de Buenos Aires en grados Celsius, y la probabilidad de lluvia (en porcentaje)

**Descripción**
Obtener del servidor la información de temperatura actual y probabilidad de lluvia, y mostrarlo en pantalla, cumpliendo con la especificación de los mockups

![image](https://user-images.githubusercontent.com/19612265/94632894-22fe9800-02a2-11eb-9bfd-b0d45c34303c.png)

Los casos de error se manejan en #5 

**Criterio de aceptación asociado**
La temperatura deberá mostrarse en grados Celsius.

**Comment by MatiasReimondo** [comment]
![4](https://user-images.githubusercontent.com/15663140/95026518-2ad68780-0668-11eb-9ba0-06ac14016a8a.jpg)
