### ISSUE TITLE
Mostrar distintas imágenes según clima actual

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#8]
Como usuario
Quiero que dependiendo del clima actual se muesrte una imagen de fondo diferente
Para que sea más intuitivo saber el clima actual

**Descripción**
Cargar varias imágenes a la aplicación (hardcodeadas) que, según la respuesta del server del clima actual, se muestren como fondo de la activity.

TBD: ¿Cómo inferir el clima actual según los datos que tenemos (temperatura y probabilidad de lluvia)?

Las imágenes deberían mantener una temática similar y tener una resolución aceptable.

**Criterio de aceptación asociado**
Las fotos deberán estar en la aplicación y tendrán un mínimo de resolución HD.

**Comment by MatiasReimondo** [comment]
![8](https://user-images.githubusercontent.com/15663140/95026851-9883b300-066a-11eb-9931-7677ab6a4e90.jpg)
![9](https://user-images.githubusercontent.com/15663140/95026853-991c4980-066a-11eb-8b70-53dee834b915.jpg)
![10](https://user-images.githubusercontent.com/15663140/95026854-99b4e000-066a-11eb-854f-12553921e01b.jpg)
