### ISSUE TITLE
Botón de actualización

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/TP0-Front#9]
Como usuario
Quiero contar con un botón de actualización
Para poder recibir la información más reciente del clima

**Descripción**
Agregar botón de actualización que realice la consulta al servidor nuevamente y actualice los datos mostrados en pantalla (temperatura #7, probabilidad de lluvia, fondo de pantalla según clima #8)

![image](https://user-images.githubusercontent.com/19612265/94633550-06635f80-02a4-11eb-8ed6-035104790945.png)

Si presiono el botón recargar debe actualizar los datos con información del servidor.

Si la consulta al servidor falla, mostrar el mismo modal que en #5 , "No fue posible conectarse al servidor, por favor reintente más tarde", y mantener la información existente.

**Criterios de aceptación**
Si presiono el botón recargar debe actualizar los datos con información del servidor.

Si presiono y no hay conectividad debe mantenerse la información existente y mostrar un mensaje toast indicando “No fue posible conectarse al servidor, por favor reintente más tarde”.

**Comment by MatiasReimondo** [comment]
![5](https://user-images.githubusercontent.com/15663140/95026531-4d68a080-0668-11eb-9455-5566f30c0fef.jpg)
![4](https://user-images.githubusercontent.com/15663140/95026532-4f326400-0668-11eb-9ceb-51a61dd23e28.jpg)
